apiVersion: v2
name: python-specific-provisioner
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: AgileLab
    url: http://agilelab.it
